// <auto-generated />
using System;
using Musicly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Musicly.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324123016_GeneralRequestSystem")]
    partial class GeneralRequestSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Musicly.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@musicly.com",
                            IsActive = true,
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Musicly.Models.CommentLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("Musicly.Models.DbTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GradientColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconSvg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("Title");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Ashes in Slow Motion.mp3",
                            Genre = "Cinematic",
                            GradientColor = "linear-gradient(135deg, #1a1a2e, #16213e, #0f3460, #e94560)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M13.5.67s.74 2.65.74 4.8c0 2.06-1.35 3.73-3.41 3.73-2.07 0-3.63-1.67-3.63-3.73l.03-.36C5.21 7.51 4 10.62 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8C20 8.61 17.41 3.8 13.5.67zM11.71 19c-1.78 0-3.22-1.4-3.22-3.14 0-1.62 1.05-2.76 2.81-3.12 1.77-.36 3.6-1.21 4.62-2.58.39 1.29.59 2.65.59 4.04 0 2.65-2.15 4.8-4.8 4.8z\"/></svg>",
                            Mood = "Melancholy",
                            Title = "Ashes in Slow Motion"
                        },
                        new
                        {
                            Id = 2,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Eclipsed Tides.mp3",
                            Genre = "Ambient",
                            GradientColor = "linear-gradient(135deg, #0c0c1d, #1b2845, #274060, #1b6ca8)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M21 14c-1.15 0-2.1-.56-2.77-1.37C17.32 13.74 16.07 15 14.5 15c-1.57 0-2.82-1.26-3.23-2.37C10.6 13.44 9.65 14 8.5 14c-1.15 0-2.1-.56-2.77-1.37C4.82 13.74 3.57 15 2 15v2c1.57 0 2.82-1.26 3.23-2.37.67.81 1.62 1.37 2.77 1.37 1.15 0 2.1-.56 2.77-1.37.41 1.11 1.66 2.37 3.23 2.37 1.57 0 2.82-1.26 3.23-2.37.67.81 1.62 1.37 2.77 1.37V14z\"/></svg>",
                            Mood = "Chill",
                            Title = "Eclipsed Tides"
                        },
                        new
                        {
                            Id = 3,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/High Octane Craic.mp3",
                            Genre = "Folk Rock",
                            GradientColor = "linear-gradient(135deg, #2d1b00, #8b4513, #d2691e, #ff8c00)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M12 3v10.55c-.59-.34-1.27-.55-2-.55-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4V7h4V3h-6z\"/></svg>",
                            Mood = "Energetic",
                            Title = "High Octane Craic"
                        },
                        new
                        {
                            Id = 4,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Blood in the Cobblestones.mp3",
                            Genre = "Dark Rock",
                            GradientColor = "linear-gradient(135deg, #1a0000, #4a0000, #8b0000, #cc0000)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M12 2c-5.33 4.55-8 8.48-8 11.8 0 4.98 3.8 8.2 8 8.2s8-3.22 8-8.2c0-3.32-2.67-7.25-8-11.8z\"/></svg>",
                            Mood = "Intense",
                            Title = "Blood in the Cobblestones"
                        },
                        new
                        {
                            Id = 5,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Zerberus 145.mp3",
                            Genre = "Electronic",
                            GradientColor = "linear-gradient(135deg, #0d0d0d, #1a1a2e, #e94560, #533483)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M7.5 5.6L10 7 8.6 4.5 10 2 7.5 3.4 5 2l1.4 2.5L5 7zm12 9.8L17 14l1.4 2.5L17 19l2.5-1.4L22 19l-1.4-2.5L22 14zM22 2l-2.5 1.4L17 2l1.4 2.5L17 7l2.5-1.4L22 7l-1.4-2.5zm-7.63 5.29a.996.996 0 0 0-1.41 0L1.29 18.96a.996.996 0 0 0 0 1.41l2.34 2.34c.39.39 1.02.39 1.41 0L16.7 11.05a.996.996 0 0 0 0-1.41l-2.33-2.35z\"/></svg>",
                            Mood = "Dark",
                            Title = "Zerberus 145"
                        },
                        new
                        {
                            Id = 6,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Sub_Zero_Velocity.mp3",
                            Genre = "Synthwave",
                            GradientColor = "linear-gradient(135deg, #001529, #003366, #00bfff, #e0f7ff)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M22 11h-4.17l3.24-3.24-1.41-1.42L15 11h-2V9l4.66-4.66-1.42-1.41L13 6.17V2h-2v4.17L7.76 2.93 6.34 4.34 11 9v2H9L4.34 6.34 2.93 7.76 6.17 11H2v2h4.17l-3.24 3.24 1.41 1.42L9 13h2v2l-4.66 4.66 1.42 1.41L11 17.83V22h2v-4.17l3.24 3.24 1.42-1.41L13 15v-2h2l4.66 4.66 1.41-1.42L17.83 13H22z\"/></svg>",
                            Mood = "Energetic",
                            Title = "Sub Zero Velocity"
                        },
                        new
                        {
                            Id = 7,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Shockwave Runway.mp3",
                            Genre = "EDM",
                            GradientColor = "linear-gradient(135deg, #0a0a0a, #ff00ff, #00ffff, #ffff00)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M7 2v11h3v9l7-12h-4l4-8z\"/></svg>",
                            Mood = "Energetic",
                            Title = "Shockwave Runway"
                        },
                        new
                        {
                            Id = 8,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Eclipsed Tides (1).mp3",
                            Genre = "Ambient",
                            GradientColor = "linear-gradient(135deg, #0a0a2a, #1e3a5f, #2196f3, #64b5f6)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M12 3a9 9 0 1 0 9 9c0-.46-.04-.92-.1-1.36a5.389 5.389 0 0 1-4.4 2.26 5.403 5.403 0 0 1-3.14-9.8c-.44-.06-.9-.1-1.36-.1z\"/></svg>",
                            Mood = "Chill",
                            Title = "Eclipsed Tides (Remix)"
                        },
                        new
                        {
                            Id = 9,
                            AddedByUserId = 1,
                            Artist = "Unknown Artist",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationSeconds = 0.0,
                            FilePath = "music/Everyone Belongs to Hell.mp3",
                            Genre = "Metal",
                            GradientColor = "linear-gradient(135deg, #0d0d0d, #2c003e, #950740, #c3073f)",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"rgba(255,255,255,0.8)\"><path d=\"M11.5 9C10.12 9 9 10.12 9 11.5s1.12 2.5 2.5 2.5 2.5-1.12 2.5-2.5S12.88 9 11.5 9zM20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-3.21 14.21l-2.91-2.91c-.69.44-1.51.7-2.39.7C9.01 16 7 13.99 7 11.5S9.01 7 11.5 7 16 9.01 16 11.5c0 .88-.26 1.69-.7 2.39l2.91 2.91-1.42 1.41z\"/></svg>",
                            Mood = "Intense",
                            Title = "Everyone Belongs to Hell"
                        });
                });

            modelBuilder.Entity("Musicly.Models.ListeningHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("ListeningHistory");
                });

            modelBuilder.Entity("Musicly.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Musicly.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Musicly.Models.PlaylistTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "TrackId")
                        .IsUnique();

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Musicly.Models.SongRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RespondedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("SongRequests");
                });

            modelBuilder.Entity("Musicly.Models.TrackComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.HasIndex("TrackId", "CreatedAt");

                    b.ToTable("TrackComments");
                });

            modelBuilder.Entity("Musicly.Models.UserTrackStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<double>("TotalListeningSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "TrackId")
                        .IsUnique();

                    b.ToTable("UserTrackStats");
                });

            modelBuilder.Entity("Musicly.Models.CommentLike", b =>
                {
                    b.HasOne("Musicly.Models.TrackComment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.DbTrack", b =>
                {
                    b.HasOne("Musicly.Models.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("Musicly.Models.ListeningHistory", b =>
                {
                    b.HasOne("Musicly.Models.DbTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.Notification", b =>
                {
                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.Playlist", b =>
                {
                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.PlaylistTrack", b =>
                {
                    b.HasOne("Musicly.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicly.Models.DbTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Musicly.Models.SongRequest", b =>
                {
                    b.HasOne("Musicly.Models.AppUser", "RespondedBy")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RespondedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.TrackComment", b =>
                {
                    b.HasOne("Musicly.Models.DbTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.UserTrackStats", b =>
                {
                    b.HasOne("Musicly.Models.DbTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicly.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Musicly.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Musicly.Models.TrackComment", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
